### ISSUE TITLE
CI Configuration

### ISSUE THREAD

**Issue by Mu7ammadAbed** [GSG-G9/dentoro#8]
## Define These global enviroment varibales at project setting 
- SECRET_KEY
- PGUSER = circleci
- PGDATABASE = circleci
## Add These configuration to .circleci/config.yml
```yml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD 
      - image: circleci/postgres:9.6-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
        
      - run: npm install
      - run: npm run build:db
      - run: npm test
```
