### ISSUE TITLE
Fix .ant-spin-container style issue

### ISSUE THREAD

**Issue by Mu7ammadAbed** [GSG-G9/dentoro#87]
There's an issue happened to the patient history table due to a style conflict with this class name `ant-spin-container` and this is the style 
```css
.ant-spin-container {
  width: 70vw;
}
``` 
at `client/src/component/ADayScheduleTable/style.css`
